# Generated by Django 3.1.4 on 2020-12-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('status', models.CharField(choices=[('پاسخ داده شده', 'پاسخ داده شده'), ('در حال بررسی', 'در حال بررسی'), ('بسته شده', 'بسته شده')], max_length=100, verbose_name='وضعیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده / نشده توسط ادمین')),
                ('is_read_by_sender', models.BooleanField(default=True, verbose_name='خوانده شده / نشده توسط فرستنده')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UTickets', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.ticket', verbose_name='مربوط به تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام های تیکت',
            },
        ),
    ]
