# Generated by Django 3.1.4 on 2020-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20201225_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('A', 'پاسخ داده شده'), ('P', 'در حال بررسی'), ('C', 'بسته شده')], max_length=100, verbose_name='وضعیت'),
        ),
    ]
